app:
  s3:
    bucket: s3-storage-service-bucket
    region: us-east-1
    endpoint-override: http://localhost:4566
  sqs:
    out-queue-name: out-queue
    in-queue-name: in-queue
    region: us-east-1
    endpoint-override: http://localhost:4566
  dynamodb:
    region: us-east-1
    endpoint-override: http://localhost:4566
